"""init migration

Revision ID: 91e31feddc9e
Revises: 
Create Date: 2023-05-12 08:31:54.788019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e31feddc9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False, comment='Никнейм'),
    sa.Column('first_name', sa.String(), nullable=True, comment='Имя'),
    sa.Column('last_name', sa.String(), nullable=True, comment='Фамилия'),
    sa.Column('api_key', sa.String(), nullable=False, comment='Ключ API, выданный пользователю'),
    sa.CheckConstraint('length(api_key) >= 30 and length(api_key) <= 256', name='api_key_length'),
    sa.CheckConstraint('length(first_name) >= 1 and length(first_name) <= 100', name='first_name_length'),
    sa.CheckConstraint('length(last_name) >= 1 and length(last_name) <= 100', name='last_name_length'),
    sa.CheckConstraint('length(nickname) >= 5 and length(nickname) <= 20', name='nickname_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('follower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Пользователь, на которого подписаны'),
    sa.Column('follower_id', sa.Integer(), nullable=False, comment='Подписчик'),
    sa.CheckConstraint('user_id <> follower_id', name='user_and_follower_not_equal'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'follower_id', name='unique_following')
    )
    op.create_table('tweet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=280), nullable=False, comment='Содержимое твита'),
    sa.Column('posted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата-время твита'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Пользователь, сделавший твит'),
    sa.CheckConstraint('length(content) >= 1', name='content_length'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.Integer(), nullable=False, comment='Твит'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Пользователь'),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweet.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tweet_id', 'user_id', name='unique_like')
    )
    op.create_table('tweet_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rel_uri', sa.String(), nullable=False, comment='Относительный URI медиа-файла'),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата-время загрузки файла'),
    sa.Column('tweet_id', sa.Integer(), nullable=True, comment='Твит'),
    sa.CheckConstraint('length(rel_uri) >= 1', name='rel_uri_length'),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet_media')
    op.drop_table('like')
    op.drop_table('tweet')
    op.drop_table('follower')
    op.drop_table('user')
    # ### end Alembic commands ###
