#
# How to optimize you piplines: https://blog.nimbleways.com/let-s-make-faster-gitlab-ci-cd-pipelines/
#

variables:
  PYTHON_IMAGE: python:3.9-alpine
  POSTGRES_IMAGE: postgres:15.2-alpine
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  WORK_DIR: ./tweetty
  POSTGRES_DB: test_db
  POSTGRES_USER: test
  POSTGRES_PASSWORD: test
  POSTGRES_URL: "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB"

image: $PYTHON_IMAGE

cache:
  key:
    files:
      - ./requirements/base.txt
      - ./requirements/ci.txt
  paths:
    - .cache/pip

before_script:
  - python --version  # for debug
  - python -m pip install --upgrade pip setuptools wheel
  - python -m pip install -r requirements/ci.txt

stages:
  - test
  - release
  - deploy
  - rollback

linting:
  stage: test
  interruptible: true
  script:
    - apk --update-cache add bash
    - chmod +x ./lint.sh
    - ./lint.sh $WORK_DIR
  only:
    - main
    - master
    - merge_requests
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\d+\.\d+\.\d+/

testing:
  extends: linting
  services:
    - $POSTGRES_IMAGE
  script:
    - pytest -v --color=yes --cov --cov-report=term-missing --cov-report=xml:coverage.xml $WORK_DIR
  # https://docs.gitlab.com/ee/ci/testing/test_coverage_visualization.html#python-example
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

release:
  stage: release
  before_script:
    # degug
    - echo $GITLAB_CI
    # install git
    - apk --update-cache add git
    # setup git
    - git config --local user.name "semantic-release"
    - git config --local user.email "semantic-release"
    - git switch $CI_COMMIT_BRANCH
    # remove unused tags
    - git tag -d $(git tag -l)
    - git pull
    # install python-semantic-release
    - python -m pip install --upgrade pip setuptools wheel
    - python -m pip install python-semantic-release~=7.34
  script:
    # semantic-release выполняет поиск коммитов от головного
    # до самого раннего нового коммита, но при этом не вкючая
    # коммиты слияния. Как следствие, коммит слияния не будет
    # учтен при вычислении новой версии.
    - semantic-release publish -v INFO
  rules:
    - if: ($CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master") && $GL_TOKEN != null && $CI_COMMIT_MESSAGE !~ /^\d+\.\d+\.\d+/
  allow_failure: true

deploy:
  stage: deploy
  variables:
    GIT_REF: $CI_COMMIT_SHORT_SHA
  before_script:
    # see https://dokku.com/docs/deployment/methods/git/#initializing-from-private-repositories
    - command -v ssh-agent > /dev/null || (apk --update-cache add openssh-client)
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh-keyscan -H -p 22 "192.168.1.35" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh dokku@192.168.1.35 "dokku git:sync --build tweetty git@$CI_SERVER_SHELL_SSH_HOST:python_advanced_diploma/tweetty.git $GIT_REF"
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master"
      when: manual
    - if: ($CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master") && $CI_COMMIT_MESSAGE =~ /^\d+\.\d+\.\d+/
      when: manual
  allow_failure: true

rollback:
  extends: deploy
  stage: rollback
  variables:
    GIT_REF: $CI_COMMIT_BEFORE_SHA
