version: "3.8"

services:
  api:
    build: .
    command: "uvicorn --host 0.0.0.0 --port 5000 --reload main:app"
    ports:
      - "5000:5000"
    environment:
      POSTGRES_URL: "postgresql://dev:dev@db:5432/tweetty"
    volumes:
      - ./tweetty/:/app/
      - ./.flake8:/.flake8
    restart: always
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tweetty
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - ~/postgres/data:/var/lib/postgresql/data
    restart: always
